### ISSUE TITLE
There is a small change, please help to check whether it is reasonable

### ISSUE THREAD

**Issue by ZhangQueque** [kinetiq/Ether.WeightedSelector#3]
![image](https://user-images.githubusercontent.com/61497473/146707630-039a4788-e028-4a79-9728-7e9f3fa054cf.png)

Change to this

![image](https://user-images.githubusercontent.com/61497473/146707755-c1d8afc4-c1cf-41b7-bb2f-1b8263f4eb31.png)

**Comment by kinetiq** [comment]
Sorry for the delay on getting back to you on this! It looks reasonable, although in another project I recently noticed some code like this was obsoleted. I will take a look and get a release out!

**Comment by kinetiq** [comment]
@ZhangQueque I have two thoughts for you on this:

- I found a discussion of your method for generating stronger seeds [here](https://stackoverflow.com/questions/4892588/rngcryptoserviceprovider-random-number-review). It seems fine, but while some people seemed to indicate that while it may be more difficult to guess a number generated in this manner, it still has flaws. But random numbers is a topic you can take to extremes.
- It seems like the main benefit to this approach is that it can yield less predictable sequences. However, I think that might not hold true if the Random() instance is re-used... Which it is.
- I am genuinely curious about what use case requires this. I am open to it. Are you constantly resetting your clock? Is this running in a cloud with a bunch of services that all have the same time? Is this used across many threads simultaneously, and they because the default strategy is time-dependent that's causing trouble? I would love to understand more.

**Comment by kinetiq** [comment]
No reply, so I'm closing this.
